name: Daily Auto Commit

on:
  schedule:
    - cron: '30 18 * * *'   # 12:00 AM IST
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set git config
        run: |
          git config --global user.name "SakshiHanwat"
          git config --global user.email "sakshi@users.noreply.github.com"

      - name: Make daily change
        run: |
          echo "Auto commit on $(date)" >> daily-log.txt

      - name: Commit and push
        run: |
          git add .
          git commit -m "Daily auto commit"
          git push
